### ISSUE TITLE
C value for SVM for VOC07

### ISSUE THREAD

**Issue by sayannag** [facebookresearch/vicreg#10]
"For VOC07 Everingham et al. (2010), we train a linear SVM with LIBLINEAR Fan et al. (2008). The images are center cropped and resized to 224 × 224, and the C values are computed with cross-validation." - this is from the VICReg paper by Bardes et al., ICLR 2022.

I am not being able to reproduce the results. It will be useful if the authors provided the code or the optimal C value which worked for them in this case.

**Comment by Adrien987k** [comment]
Hi,

I used the VISSL library (https://github.com/facebookresearch/vissl) with the following config file:
https://github.com/facebookresearch/vissl/blob/main/configs/config/benchmark/linear_image_classification/voc07/eval_resnet_8gpu_transfer_voc07_svm.yaml
So the C values are: [0.01, 0.1, 1.0, 2, 5, 10, 15, 20, 50, 100, 1000]

If you want to reproduce the results you need to install VISSL, and convert the pretrained ResNet-50 model to the VISSL format.

**Comment by sayannag** [comment]
Thank you so much for your response. I have never used VISSL before. Can you please provide me some leads on how to convert my pre-trained weights into VISSL format, prepare the config file for different tasks (linear classification, semi-supervised classification, segmentation) on different datasets and run on my local university cluster? Thanks again.
