### ISSUE TITLE
Questions about loss's range of experience

### ISSUE THREAD

**Issue by benyang0506** [facebookresearch/vicreg#14]
In my experiment, the cov_loss is about 1e-5 within the first 10 epochs and then became 0, I wonder the magnitude of your cov_loss. Thank you!

**Comment by Adrien987k** [comment]
Hi,

A loss of 0 most likely indicates a collapse of the representations. the magnitude of the loss depends on your data, but the cov_loss should be stable throughout the training, only the inv_loss significantly decreases.

**Comment by dc250601** [comment]
In my case the Cov_loss is slowly increasing while the other two are slowly going down. @Adrien987k  Is it normal to see such a phenomenon? In about 20 epochs it has increased from 2.6 to 6.5.
