### ISSUE TITLE
Issues in repreducing object detection results on VOC2007+12

### ISSUE THREAD

**Issue by niuchuangnn** [facebookresearch/vicreg#15]
Dear VICReg authors, thanks for sharing the codes of this great work! I have strictly followed the parameter settings for the object detection task on VOC2007+12 described in the paper and initialized the model with the provided VICReg model in this repo. However, I achieved only 79.0734 mAP50 using detectron2, lower than the reported results 82.4 in Table 2. Could you please give some guidance or share your detectron2 config file to reproduce the result? Thanks in advance!

**Comment by MaitaYuki** [comment]
@niuchuangnn , did you figure out how to reproduce the object detection results on VOC dataset? Can you share your findings and codes?

**Comment by niuchuangnn** [comment]
@MaitaYuki I cannot reproduce the results yet!

**Comment by MaitaYuki** [comment]
@niuchuangnn ,

Thanks for your fast response!
You achieved 79.0734 mAP50 using detectron2. Can you share with me your training parameter configure file that you used for your training? When I trained with the configure file [pascal_voc_R_50_C4_24k_moco.yaml] from (https://github.com/WXinlong/DenseCL/blob/main/benchmarks/detection/configs/pascal_voc_R_50_C4_24k_moco.yaml), I got even lower performance. 
Thanks!
