### ISSUE TITLE
Discrepancy with paper for covariance loss

### ISSUE THREAD

**Issue by paolomandica** [facebookresearch/vicreg#16]
Hi,

I noticed a difference between the code ([main_vicreg.py#L202](https://github.com/facebookresearch/vicreg/blob/main/main_vicreg.py#L202)) and the Algorithm 1 in the paper where the subtraction of the mean from $x$ and $y$ is performed after the variance loss.

Could you check and let me know which one is correct?
Thank you for your time,
Paolo

**Comment by ayhyap** [comment]
This is late, but subtraction of mean does not affect variance calculations, so it shouldn't matter which order it goes in.
But yes it should be grouped with the variance loss for clarity.
