### ISSUE TITLE
Transfer learning results

### ISSUE THREAD

**Issue by EavnJeong** [facebookresearch/vicreg#17]
I used this code to get the classification results of the paper`s table2(transfer learning results)

However, the results are quite different.

                      Paper       Try                                  
    INat18            47%         10%
    Places205         54.3%       41%

Table2: "linear classification tasks on top of frozen representations"
C ADDITIONAL IMPLEMENTATION DETAILS
    C.3 TRANSFER LEARNING
        Linear classification : "experiment detail"

Following above sentence and C.3 paragraph, I tried two dataset(INat18, Places205)
      1. Load pretrained by Imagenet weight in this repo.
      2. Frozen all weights in resnet50 backbone.
          (It is not updated at all.)
      3. Training with Linear Layer.

I wonder is there anything I miss?
Is this process right access?

**Comment by Adrien987k** [comment]
Hi,

The process is correct but there are a lot of hidden details such as the data augmentation parameters.
I used the VISSL library (https://github.com/facebookresearch/vissl) to run these experiments.

Try to use VISSL and plug the parameters in the paper with the following config file:
https://github.com/facebookresearch/vissl/blob/main/configs/config/benchmark/linear_image_classification/inaturalist18/eval_resnet_8gpu_transfer_inaturalist18_linear.yaml

Before that you only need to convert the pytorch checkpoint to vissl checkpoint. I can send you the vissl checkpoint if you want.
