### ISSUE TITLE
torchvision dependencies mismatch with 'InterpolationMode' class

### ISSUE THREAD

**Issue by hugoych** [facebookresearch/vicreg#19]
Hi, 
Thanks for the repo!

I saw from the README that the only requirement was `pytorch==1.7.1` but I think there is also an implicit requirement on the vision library: `torchvision >=0.9.0`. 

Indeed from pytorch official installation guide pytorch 1.7.1 should be installed with torchvision 0.8.2 (see [doc](https://pytorch.org/get-started/previous-versions/)).  However, according to the torchvision [repo](https://github.com/pytorch/vision/blob/v0.9.0/torchvision/transforms/functional.py), the class `InterpolationMode`, only appears in version 0.9.0.

This leads to an `ImportError` in  [augmentations.py](https://github.com/facebookresearch/vicreg/blob/a73f567660ae507b0667c68f685945ae6e2f62c3/augmentations.py#L11). 

Do you know the reason behind this and can you confirm which version of torchvision you are using? 

Thanks!

**Comment by Adrien987k** [comment]
Hi,

Thanks for pointing this out! The correct pytorch version is actually 1.8.1 and torchvision is 0.9.1. 
I have updated the readme.
