### ISSUE TITLE
Non-symmetric Augmentations

### ISSUE THREAD

**Issue by EmreTaha** [facebookresearch/vicreg#3]
Hi,
In the paper, you mentioned that the augmentations are symmetrized but in the code probabilities for blur and polarization are not symmetric (similar to BYOL). Is there a reason for that?

**Comment by Adrien987k** [comment]
Hi,
Yes you are right, I am using the same set of augmentation as BYOL uses because I released it works slightly better in some cases than what is described in the paper. I will make it clear in the README.

I am closing the issue, if you have more questions please contact me at abardes@fb.com
