### ISSUE TITLE
Unable to load the pre-trained models : resnet50() returns tuple not model

### ISSUE THREAD

**Issue by lkshrsch** [facebookresearch/vicreg#5]
Following the instructions on the README I am trying to download the pretrained models

```
import torch
resnet50 = torch.hub.load('facebookresearch/vicreg:main', 'resnet50')
```
This fails because "tuple" has no attribute load_state_dict(), pointing to line 21 on script vicreg/hubconf.py

In fact, the function resnet50() defined in the script /main/resnet.py returns a tuple 

```
def resnet50(**kwargs):
    return ResNet(Bottleneck, [3, 4, 6, 3], **kwargs), 2048
```

In order to make this work, I had to modify the function resnet50() in hubconf.py:

```

def resnet50(pretrained=True, **kwargs):
    model = resnet.resnet50(**kwargs)
    if pretrained:
        state_dict = torch.hub.load_state_dict_from_url(
            url="https://dl.fbaipublicfiles.com/vicreg/resnet50.pth",
            map_location='cpu',
        )
        model[0].load_state_dict(state_dict, strict=True)     --> Grab first element of tuple!
    return model
```

**Comment by Adrien987k** [comment]
Hi,

Thanks for raising this issue! It is now fixed.

**Comment by ColinConwell** [comment]
This issue seems to have persisted. Calling:

```python
import torch
resnet50 = torch.hub.load('facebookresearch/vicreg:main', 'resnet50')
```
raises the error:

AttributeError: 'tuple' object has no attribute 'load_state_dict'
