### ISSUE TITLE
Readme commands to load pretrained models on PyTorch Hub (resnet50x2 and resnet200x2) not working

### ISSUE THREAD

**Issue by xavibou** [facebookresearch/vicreg#9]
Hi,

When running the commands specified on the readme file to load the pretrained models on PyTorch Hub, they fail for resnet50x2 and resnet200x2. The issue is that the callable methods that load such models in hubconf.py are not called  'resnet50x2' and  'resnet200x2' but 'resnet50x2' and  'resnet200x2', respectively.

I got it working by changing the original commands shown in the readme by the following:

```
import torch
resnet50 = torch.hub.load('facebookresearch/vicreg:main', 'resnet50')
resnet50x2 = torch.hub.load('facebookresearch/vicreg:main', 'resnet50w2')
resnet200x2 = torch.hub.load('facebookresearch/vicreg:main', 'resnet200w2')
```

Where I just replaced the 'x' by 'w' in 'resnet50x2' and  'resnet200x2'.

Thank you,
Xavi

**Comment by Adrien987k** [comment]
Should be fixed now. Thanks.
